Repository k0sproject/k0sctl, pull requests merged in 2022-04, with the labels that each got.

#365 Remove executable bit from k0s.yaml
  phase/configure_k0s.go
Labels: chore

#359 Add sudo to chmod when upgrading k0s
  pkg/apis/k0sctl.k0sproject.io/v1beta1/cluster/host.go
Labels: bug

#366 Fix tee error when uploading k0s binaries
  go.mod
  go.sum
  phase/gather_k0s_facts.go
  phase/upload_binaries.go
Labels: bug, enhancement

#373 Remove backup from host after download
  phase/backup.go
Labels: bug, enhancement

#371 Fix double binary upload/download
  phase/download_k0s.go
Labels: bug
