Repository k0sproject/k0sctl, pull requests merged in 2022-02, with the labels that each got.

#313 Fix hostname-override kubelet parameter passing
  pkg/apis/k0sctl.k0sproject.io/v1beta1/cluster/host.go
Labels: bug

#318 Fix upload_tests if /tmp is empty
  pkg/apis/k0sctl.k0sproject.io/v1beta1/cluster/uploadfile_test.go
Labels: chore

#317 Fix k0s version sorting
  cmd/flags.go
  go.mod
  go.sum
  integration/github/github.go
  phase/gather_k0s_facts.go
  phase/validate_facts.go
  pkg/apis/k0sctl.k0sproject.io/v1beta1/cluster/k0s.go
Labels: bug

#325 Fix missing sudo from chmod during binary uploads
  phase/upload_binaries.go
Labels: bug

#329 Drop images from k0s init --k0s config template
  cmd/init.go
Labels: enhancement
