Repository k0sproject/k0sctl, pull requests merged in 2023-09, with the labels that each got.

#549 Set a conenct timeout of 20 seconds HTTPStatus
  configurer/linux.go
Labels: enhancement

#553 Bump rig to v0.13.0
  go.mod
  go.sum
Labels: bug, enhancement, chore, dependencies

#554 Conditional iptables installation based on k0s version
  phase/prepare_hosts.go
  pkg/apis/k0sctl.k0sproject.io/v1beta1/cluster/host.go
Labels: enhancement

#497 Extract logic from cmd into reusable actions
  action/apply.go
  action/backup.go
  action/config_edit.go
  action/config_status.go
  action/kubeconfig.go
  action/reset.go
  cmd/apply.go
  cmd/backup.go
  cmd/config_edit.go
  cmd/config_status.go
  cmd/flags.go
  cmd/kubeconfig.go
  cmd/reset.go
  phase/manager.go
Labels: chore

#556 Validate quote balance in installFlags
  pkg/apis/k0sctl.k0sproject.io/v1beta1/cluster/host.go
  pkg/apis/k0sctl.k0sproject.io/v1beta1/cluster/host_test.go
Labels: enhancement
