Repository k0sproject/k0sctl, pull requests merged in 2023-01, with the labels that each got.

#439 Use --data-dir from installFlags for token creation
  pkg/apis/k0sctl.k0sproject.io/v1beta1/cluster/k0s.go
Labels: bug

#443 Unify the way k0s binary is installed after upload or download
  cmd/apply.go
  configurer/linux.go
  go.sum
  phase/download_k0s.go
  phase/install_binaries.go
  phase/upgrade_controllers.go
  phase/upgrade_workers.go
  phase/upload_binaries.go
  pkg/apis/k0sctl.k0sproject.io/v1beta1/cluster/host.go
Labels: enhancement, chore

#446 Add host.DataDir
  README.md
  cmd/backup.go
  cmd/config_edit.go
  cmd/config_status.go
  configurer/linux.go
  phase/configure_k0s.go
  phase/install_controllers.go
  phase/install_workers.go
  phase/prepare_hosts.go
  phase/reset_controllers.go
  phase/reset_leader.go
  phase/reset_workers.go
  pkg/apis/k0sctl.k0sproject.io/v1beta1/cluster/host.go
  pkg/apis/k0sctl.k0sproject.io/v1beta1/cluster/host_test.go
  pkg/apis/k0sctl.k0sproject.io/v1beta1/cluster/k0s.go
Labels: enhancement

#441 Retire upgrade test from k0s v0.11.0
  .github/workflows/go.yml
Labels: chore

#447 Use --delete-emptydir-data instead of deprecated --delete-local-data
  pkg/apis/k0sctl.k0sproject.io/v1beta1/cluster/host.go
Labels: chore

#453 Validate host private address uniqueness
  phase/validate_hosts.go
Labels: enhancement

#455 fix: localhost panic nil pointer dereference
  pkg/apis/k0sctl.k0sproject.io/v1beta1/cluster/host.go
Labels: bug

#457 Update copyright year to 2023
  LICENSE
  cmd/flags.go
Labels: chore
